name: 'dev'

on:
  push:
  
jobs:
  build-run:
    runs-on: self-hosted
    
    env:
      name: "dev-${{ github.sha }}"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: 'Run images'
        run: |
          docker build -t ${{ env.name }}:${{ github.sha }}  .
          docker run -d -p 3000:3000 --name ${{ env.name }}  ${{ env.name }}:${{ github.sha }}  
  build-push:
    runs-on: self-hosted

    env:
      dockerhub-username: "arturgrigoryan1"
      repository-name: "news_letter"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: 'Build and push'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.dockerhub-username }}/${{ env.repository-name }}:${{ github.sha }}
