name: 'dev'

on:
  push:
  
env:
  environment: dev
  
jobs:
  development:
    runs-on: self-hosted
    env:
      anun: "${{ env.environment }}-${{ github.sha }}"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: 'Run our images'
        run: |
          docker build -t ${{ env.anun }} .
          docker run -d -p 3000:3000 --name ${{ env.anun }} ${{ env.anun }}:latest   
          
      # - name: 'Login to Docker Hub'
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # - name: 'Build and push'
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: arturgrigoryan1/news_letter:latest
