name: 'prod'
on: 
  push:
    tags:
      -  'v[0-9]+.[0-9]+.[0-9]+'
      
jobs:
  deploy:
     runs-on: self-hosted
     env:
      name: "prod-${{  github.ref_name }}"
     steps:
       - name: 'Run image from Dockerhub'
         run: |
           docker run -d -p 8080:3000 --name ${{ env.name }}  arturgrigoryan1/news_letter:${{ github.sha }} 
