name: 'staging'
on: 
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+'
      
jobs:
  staging:
     runs-on: self-hosted
     env:
      anun: "staging-${{  github.ref_name }}"
     steps:
       - name: 'Run Dockerhub image'
         run: |
           docker run -d -p 3002:3000 --name ${{ env.anun }}  arturgrigoryan1/news_letter:${{ github.sha }} 
