name: 'staging'
on: 
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+'
      
jobs:
  staging:
     runs-on: self-hosted
     env:
      name: "staging-${{  github.ref_name }}"
      dockerhub-username: "arturgrigoryan1"
      repository-name: "news_letter"
     steps:
       - name: 'Run Dockerhub image'
         run: |
           docker run -d -p 3002:3000 --name ${{ env.name }}  ${{ env.dockerhub-username }}/${{ env.repository-name }}:${{ github.sha }} 
