name: 'test'

on:
  workflow_dispatch:
    
  
jobs:
  testing:
    runs-on: self-hosted
    
    env:
      name: "test-${{ github.sha }}"
      dockerhub-username: "arturgrigoryan1"
      repository-name: "news_letter"
    steps:
      - name: 'Run Dockerhub image'
        run: |
          docker run -d -p 3001:3000 --name ${{ env.name }}  ${{ env.dockerhub-username }}/${{ env.repository-name }}:${{ github.sha }} 
